language: python
python:
    - "2.7"
    - "3.3"
before_install:
    - virtualenv ./pyenv --distribute
    - source ./pyenv/bin/activate
install:
    - pip install -e .
    - pip install nose coverage
    - pip install python-dateutil coveralls unicodecsv
before_script:
    - nosetests --version
script:
    - nosetests --with-coverage --cover-package=babbage
after_success:
    - coveralls
